name: Salon Onze
favicon: null
layout_spectrum: 0.7339605011511594
typography_spectrum: 0.4930732799693942
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.11861452087759972
  lightness: 0.43529905239120126
  saturation: 0.04111606231890619
  rhythmicContrast: 0.2728271910455078
purpose: []
