name: Salon Onze
favicon: null
layout_spectrum: 0.8117927676066756
typography_spectrum: 0.7814538297243416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6322952504269779
  lightness: 0.1206930223852396
  saturation: 0.394150365376845
  rhythmicContrast: 0.33258064300753176
purpose: []
