name: Salon Onze
favicon: null
layout_spectrum: 1
typography_spectrum: 0.679410747718066
title: Beauty
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfe'
    - '#262a2b'
    - '#9acde0'
    - '#b6ae9b'
    - '#906b37'
  brandStrength: 0.4375
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
