name: Salon Onze
favicon: null
layout_spectrum: 0.7044693778734654
typography_spectrum: 0.7952620121650398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9379655972588807
  lightness: 0.5239468670915812
  saturation: 0.23614615900442004
  rhythmicContrast: 0.2240437539294362
purpose: []
