name: Salon Onze
favicon: null
layout_spectrum: 0.7219108392018825
typography_spectrum: 0.679410747718066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8333213648293167
  lightness: 0.31766037829220295
  saturation: 0.7873202150221914
  rhythmicContrast: 0.5628874849062413
purpose: []
