name: Salon Onze
favicon: null
layout_spectrum: 0.39123083907179534
typography_spectrum: 0.8225729428231716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9453145945444703
  lightness: 0.9246634268201888
  saturation: 0.43139111530035734
  rhythmicContrast: 0.886951029067859
purpose: []
