name: Salon Onze
favicon: null
layout_spectrum: 1
typography_spectrum: 0.679410747718066
title: Beauty
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dedfe4'
    - '#121318'
    - '#8e8a81'
    - '#b4b7bc'
    - '#616362'
  brandStrength: 0.8333213648293167
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
