name: Salon Onze
favicon: null
layout_spectrum: 0.617191438563168
typography_spectrum: 0.11097395070828497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7791524601634592
  lightness: 0.33448980026878417
  saturation: 0.31492366711609066
  rhythmicContrast: 0.45994093688204885
purpose: []
